### ISSUE TITLE
namespace html ?

### ISSUE THREAD

**Issue by terroo** [alialib/alia#54]
After including in the header why does it not recognize the html:: namespace?

![captura-29-01-2022-02-01-40](https://user-images.githubusercontent.com/41500739/151648132-2a2a14db-13f7-44e1-8b6e-f049762ec7c0.png)

**Comment by tmadden** [comment]
Hi! Thanks for trying out alia. :-)

The HTML bindings for alia aren't bundled in the with core or alia itself, so you don't get them when you include "alia.hpp". They also don't work outside of Emscripten right now, so the best way to try them out is via this starter kit:

https://github.com/alialib/alia-html-starter

**Comment by terroo** [comment]
OK thanks! I am going to try!
